### ISSUE TITLE
conflict with symfony version 3.2.x-dev

### ISSUE THREAD

**Issue by flug** [greg0ire/enum#51] opened 2016-09-14 08:21 UTC
Hi , 
I think that there is a problem of compatibility with the new version of symfony -> version 3.2.x-dev and the enum -> v3.1.0 version

```sh 
  Problem 1
    - Installation request for symfony/symfony 3.2.x-dev -> satisfiable by symfony/symfony[3.2.x-dev].
    - greg0ire/enum v3.1.0 conflicts with symfony/symfony[3.2.x-dev].
    - Installation request for greg0ire/enum ^3.1 -> satisfiable by greg0ire/enum[v3.1.0].
```

**Comment by greg0ire** [comment] 2016-09-14 08:29
Why would you use a development version of symfony?

**Comment by flug** [comment] 2016-09-14 08:52
To prepare a possible migration of the 3.1 to 3.2 :D

**Comment by greg0ire** [comment] 2016-09-14 08:57
3.2 is a minor version, which means there should be literally no code to change before updating to `3.2.0`. But anyway, I don't understand where that conflict comes from, that's strange indeed.

**Comment by flug** [comment] 2016-09-14 09:00
Yes Yes, I don't understand me too :-/

**Comment by greg0ire** [comment] 2016-09-14 09:04
Related : https://github.com/composer/composer/issues/5505

**Comment by greg0ire** [comment] 2016-09-14 09:45
As @Soullivaneuh points out, what is strange is that [the 3.2 build passes](https://travis-ci.org/greg0ire/enum/jobs/159825828)

**Comment by greg0ire** [comment] 2016-09-14 10:20
Since this looks like a bug in Composer, and you're trying to do something a bit strange, maybe you could use an inline alias to alias symfony to something stable like `3.2.0`?

**Comment by flug** [comment] 2016-09-14 12:19
Hum you are tested on [symfony-standard](https://github.com/symfony/symfony-standard) ? Because it is on him that I had the problem

**Comment by greg0ire** [comment] 2016-09-14 12:22
I tested and reproduced your problem. What I am saying is that you could probably work around it with an inline alias.

**Comment by greg0ire** [comment] 2016-09-14 12:27
I tested with an inline alias, it does not seem to work :(

> As @Soullivaneuh points out, what is strange is that the 3.2 build passes

There is a `SYMFONY_VERSION` variable in `.travis.yml`, but it does not seem to be used at all :P

**Comment by flug** [comment] 2016-09-14 12:32
:cry: This is very strange... :neckbeard:

**Comment by greg0ire** [comment] 2016-09-14 13:40
Let's start by fixing this, see #59

**Comment by flug** [comment] 2016-09-14 13:50
Euh you're still in 3.1 ? no ? https://github.com/greg0ire/enum/pull/59/files#diff-354f30a63fb0907d4ad57269548329e3R30

**Comment by greg0ire** [comment] 2016-09-14 14:03
This is the legacy branch. I just merged it in master #60 , and [the 3.2 job fails](https://travis-ci.org/greg0ire/enum/jobs/159879790), so things are looking a bit more normal now.

**Comment by flug** [comment] 2016-09-14 14:10
ahh yes yes it's more explicit :D

**Comment by greg0ire** [comment] 2016-09-14 14:51
@flug : #63 should fix that :)

**Closed** 2016-09-14 15:05 UTC

**Comment by greg0ire** [comment] 2016-09-14 15:09
@flug fixed : https://github.com/greg0ire/enum/releases/tag/v3.1.1

Thanks for reporting this!

**Comment by flug** [comment] 2016-09-14 15:34
cool :kissing_closed_eyes: :+1:
